name: Deploy LangGraph Bot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python -m pytest tests/ || echo "No tests found"
    
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    
    - name: Install LangGraph CLI
      run: pip install langgraph-cli
    
    - name: Deploy to LangGraph Platform
      run: |
        echo "${{ secrets.LANGCHAIN_API_KEY }}" | langgraph auth login --stdin
        langgraph deploy --wait
